### ISSUE TITLE
I can't install this plug-in. Can I have a. jar?

### ISSUE THREAD

**Issue by sqh111** [BIOP/ijp-frc#4]

**Comment by NicoKiaru** [comment]
Hello, can't you use the PTBIOP update site ?

If you need the jar, you can download it here: https://maven.scijava.org/#nexus-search;gav~ch.epfl.biop~FRC_~~~~kw,versionexpand

**Comment by NicoKiaru** [comment]
The problem with using the jar is that you may also need other dependencies:

https://github.com/BIOP/ijp-frc/blob/master/pom.xml

**Comment by sqh111** [comment]
Ask a simple question, I only have a sim image now, and use this plug-in to calculate FRC. But I see that I have to input two images. Can these two images be the same? Still have to make any difference.

**Comment by lacan** [comment]
The images should be the same objects, but two separate acquisitions. The whole point of the method is to measure the correlation between the two images until it disappears, which we can then assume it's the noise. If you compare the two exact same images, you will get an artificial full resolution, which will not be useful.

**Comment by sqh111** [comment]
Thank you for your answer. I understand.
